EXTRA_CFLAGS += \
             -I$(M) \
             -I$(M)/../include \
             -I$(M)/../../include 
EXTRA_CFLAGS += -DGIT_VERSION=\"$(GIT_VERSION)\"

obj-m += cvorg.o

cvorg-objs := cvorg-func.o cvorg_sysfs.o clkgen.o cvorgdrv.o 
