EXTRA_CFLAGS=-I $(src)/../../tpci200/include
KBUILD_EXTRA_SYMBOLS= $(src)/../../tpci200/driver/Module.symvers
EXTRA_CFLAGS += -DGIT_VERSION=\"$(GIT_VERSION)\"

obj-m := ipoctal.o
ipoctal-objs := ipoctal_drvr.o 


