#================================================================
# Makefile to produce standard CTR-P test program
#================================================================

CPU=L865

include /acc/dsc/src/co/Make.auto

CFLAGS= -g -Wall -I/acc/local/$(CPU)/include/tgm -I../driver -I. \
	-DCTR_VME -DPS_VER -DEMULATE_LYNXOS_ON_LINUX

LDLIBS= -ltgm -lvmtg -ltgv -lerr -lerr_dummy -lX11 -lm

ALL  = ctrvtest.$(CPU) \
       CtrReadInfo.$(CPU) \
       CtrWriteInfo.$(CPU)

SRCS = ctrtest.c CtrCmds.c CtrOpen.c DoCmd.c GetAtoms.c Cmds.c plx9030.c
HDRS = Cmds.h

TEST = ctrtest.c CtrCmds.c CtrOpen.c DoCmd.c GetAtoms.c Cmds.c plx9030.c
READ = CtrReadInfo.c CtrOpen.c
WRIT = CtrWriteInfo.c CtrOpen.c

all: $(ALL)

clean:
	$(RM) $(ALL) $(BAKS) ctrvtest.$(CPU).o

# Run on Workstation only

ctrvtest.$(CPU).o: $(TEST) $(HDRS)

CtrReadInfo.$(CPU).o: $(READ) $(HDRS)

CtrWriteInfo.$(CPU).o: $(WRIT) $(HDRS)

install: ctrvtest.$(CPU)
	dsc_install $(ALL) /acc/dsc/lab/$(CPU)/ctr
	dsc_install $(ALL) /acc/dsc/oper/$(CPU)/ctr
	dsc_install $(ALL) /acc/dsc/oplhc/$(CPU)/ctr
