ccflags-y += -I$(M)
ccflags-y += -I$(M)/../include
ccflags-y += -I$(M)/../../include
ccflags-y += -DGIT_VERSION=\"$(GIT_VERSION)\"

obj-m := sis33.o sis3320.o sis3300.o

sis33-objs := sis33_core.o sis33_dma.o sis33_sysfs.o sis33_compat_ioctl.o
