#include "vmeio.h"
#include "ctc_regs.h"

struct encore_reginfo ctc_registers[] = {

[STATUS] = {
	.name			= "STATUS",
	.rwmode			= "rc",
	.block			= 0,
	.block_address_space	= 1,
	.block_offset		= 0x0,
	.register_offset	= 0x0,
	.offset			= 0x0,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "Hardware version",
	.data_width		= 32,
},

[CNTR_ENABLE] = {
	.name			= "CNTR_ENABLE",
	.rwmode			= "rw",
	.block			= 0,
	.block_address_space	= 1,
	.block_offset		= 0x0,
	.register_offset	= 0x4,
	.offset			= 0x4,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "Enable/disable output channel",
	.data_width		= 32,
},

[confChan] = {
	.name			= "confChan",
	.rwmode			= "rw",
	.block			= 1,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x0,
	.offset			= 0x8,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "Select External start (i.e. input channel) and Clock1/Clock2 settings",
	.data_width		= 32,
},

[clock1Delay] = {
	.name			= "clock1Delay",
	.rwmode			= "rw",
	.block			= 1,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x4,
	.offset			= 0xc,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "How many ticks to wait (i.e. delay) for the 1'st counter",
	.data_width		= 32,
},

[clock2Delay] = {
	.name			= "clock2Delay",
	.rwmode			= "rw",
	.block			= 1,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x8,
	.offset			= 0x10,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "How many ticks to wait (i.e. delay) for the 2'nd counter",
	.data_width		= 32,
},

[outputCntr] = {
	.name			= "outputCntr",
	.rwmode			= "r",
	.block			= 1,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0xc,
	.offset			= 0x14,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "Output pulse counter that occured in the channel",
	.data_width		= 32,
},

[cntr1CurVal] = {
	.name			= "cntr1CurVal",
	.rwmode			= "r",
	.block			= 1,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x10,
	.offset			= 0x18,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "Current value of the 1'st counter",
	.data_width		= 32,
},

[cntr2CurVal] = {
	.name			= "cntr2CurVal",
	.rwmode			= "r",
	.block			= 1,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x14,
	.offset			= 0x1c,
	.wordsize		= "long",
	.depth			= 0x0,
	.description		= "Current value of the 2'nd counter",
	.data_width		= 32,
},

[channel_1] = {
	.name			= "channel_1",
	.rwmode			= "rw",
	.block			= 2,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x0,
	.offset			= 0x8,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 1",
	.data_width		= 32,
},

[channel_2] = {
	.name			= "channel_2",
	.rwmode			= "rw",
	.block			= 3,
	.block_address_space	= 1,
	.block_offset		= 0x20,
	.register_offset	= 0x0,
	.offset			= 0x20,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 2",
	.data_width		= 32,
},

[channel_3] = {
	.name			= "channel_3",
	.rwmode			= "rw",
	.block			= 4,
	.block_address_space	= 1,
	.block_offset		= 0x38,
	.register_offset	= 0x0,
	.offset			= 0x38,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 3",
	.data_width		= 32,
},

[channel_4] = {
	.name			= "channel_4",
	.rwmode			= "rw",
	.block			= 5,
	.block_address_space	= 1,
	.block_offset		= 0x50,
	.register_offset	= 0x0,
	.offset			= 0x50,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 4",
	.data_width		= 32,
},

[channel_5] = {
	.name			= "channel_5",
	.rwmode			= "rw",
	.block			= 6,
	.block_address_space	= 1,
	.block_offset		= 0x68,
	.register_offset	= 0x0,
	.offset			= 0x68,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 5",
	.data_width		= 32,
},

[channel_6] = {
	.name			= "channel_6",
	.rwmode			= "rw",
	.block			= 7,
	.block_address_space	= 1,
	.block_offset		= 0x80,
	.register_offset	= 0x0,
	.offset			= 0x80,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 6",
	.data_width		= 32,
},

[channel_7] = {
	.name			= "channel_7",
	.rwmode			= "rw",
	.block			= 8,
	.block_address_space	= 1,
	.block_offset		= 0x98,
	.register_offset	= 0x0,
	.offset			= 0x98,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 7",
	.data_width		= 32,
},

[channel_8] = {
	.name			= "channel_8",
	.rwmode			= "rw",
	.block			= 9,
	.block_address_space	= 1,
	.block_offset		= 0xb0,
	.register_offset	= 0x0,
	.offset			= 0xb0,
	.wordsize		= "long",
	.depth			= 0x6,
	.description		= "All registers of channel 8",
	.data_width		= 32,
},

[ALL_CHANNELS] = {
	.name			= "ALL_CHANNELS",
	.rwmode			= "rw",
	.block			= 10,
	.block_address_space	= 1,
	.block_offset		= 0x8,
	.register_offset	= 0x0,
	.offset			= 0x8,
	.wordsize		= "long",
	.depth			= 0x30,
	.description		= "All CTC channels to access in one chunk",
	.data_width		= 32,
},

};

int ctc_nregs = sizeof(ctc_registers)/sizeof(ctc_registers[0]);
