EXTRA_CFLAGS=-I $(src)/../../include
obj-m += modulbus_register.o 
obj-m += mod-pci.o vmodio.o 
obj-m += vmodttl.o vmoddor.o vmod12a2.o

vmodttl-objs := lunargs.o vmodttldrvr.o
vmod12a2-objs := lunargs.o vmod12a2drvr.o
