#!/bin/sh

echo "======================================================="
echo "install CTRP/I driver ctrp.ko                          "
echo "install No xml file will be used                       "
echo "======================================================="

echo 8 > /proc/sys/kernel/printk

/sbin/insmod /usr/local/drivers/ctr/ctrp.ko debug=0 recover=0 modules=1

MAJOR=`cat /proc/devices | awk '{if ($2 == "ctrp") printf $1}'`
if [ -z "$MAJOR" ]; then
        echo "driver ctr not installed !"
        exit 2
fi
for m in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do \
	rm -f /dev/ctrp.$m; \
	/bin/mknod  -m 0666 /dev/ctrp.$m c ${MAJOR} $m; \
done
