#!/bin/sh

echo "======================================================="
echo "install CTRV driver ../ctrv/ctrv.ko                    "
echo "install modules=1 (1 module will auto install)         "
echo "install infoaddr=0 (No xml file will be used)          "
echo "======================================================="

SRC=/acc/src/dsc/drivers/cohtdrep/lewis/modpars/ctr/driver
CPU=L865
KVER=2.6.24.7-rt27

echo 8 > /proc/sys/kernel/printk

#/sbin/insmod $SRC/$CPU/$KVER/ctrv.ko modules=2
/sbin/insmod $SRC/$CPU/$KVER/ctrv.ko luns=1,2 vme1=0xC00000,0xC10000 vme2=0x100,0x200 vecs=0xC8,0xC9

MAJOR=`cat /proc/devices | awk '{if ($2 == "ctrv") printf $1}'`
#echo Making nodes for ${MODULE} major device ctr ${MAJOR}

for m in 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16; do \
	rm -f /dev/ctr.$m; \
	mknod  -m 0666 /dev/ctr.$m c ${MAJOR} $m; \
done
