EXTRA_CFLAGS = -DHARD_FLOAT -mhard-float -DCOMPILE_TIME=$(shell date +%s)

obj-m := ctrv.o ctrp.o
ctrv-y := ctrvdrvr.o
ctrp-y := ctrpdrvr.o

CFLAGS_ctrvdrvr.o := -DCTR_VME
CFLAGS_ctrpdrvr.o := -DCTR_PCI
