#ifdef __Lynx__
/* for __inb, __outb etc... */
#include "dg/port_ops_lynx.h"
#else  /* __linux__ */
#include "dg/port_ops_linux.h"
#include "dg/swab-extra-linux.h"
#endif
#include "CvorbDrvr.h"
#include "CvorbUserDefinedDrvr.h"
#include "CvorbVersionDrvr.h"

int sem_drvr = 1; /* initial semaphore value */

/* next are for timing measurements */
#define TSTR_LEN 32 /* time string lengths */
/* time statistic string */
char GlobTimeStatS[TSTR_LEN] = { [0 ... sizeof(GlobTimeStatS)-1] = 0 };
#ifdef __Lynx__
unsigned long GlobStartS = 0, GlobEndS = 0; /* seconds */
unsigned int  GlobStartN = 0, GlobEndN = 0; /* nanoseconds */
unsigned int  GlobCalVal = 0; /* timing measurements calibration value */
#else /* __linux__ */
static struct timespec _t_beg, _t_end, _t_delta;
static s64 _ac_etime;
#endif	/* __Lynx__ */

/* -------> CVORB Driver version info <------- */
/* driver compilation date and time */
static char Cvorb_compile_date[]  = __DATE__;
static char Cvorb_compile_time[]  = __TIME__;

/* which driverGen version was used to generate current code */
static const char Cvorb_version[] = "v2.6.11";

/* generation date in hex and human representation */
static const char Cvorb_generation_time_str[] = "Tue Jan 12 10:00:12 2010";
#define CVORB_GENERATION_TIME_HEX 0x4b4c3a1c
/* ------------------------------------------------------------------------- */

/* to suppress implisit declaration warnings */
extern int nanotime(unsigned long *);
extern int ksprintf(char *, char *, ...);
extern int unmapVmeAddr(DevInfo_t*) __attribute__ ((weak));

/**
 * @brief Current driver/simulator version.
 *
 * @param vp -- if not @e NULL - driver version string will be placed here
 *
 * If @b vp is @e NULL, then driver compilation date and @e driverGen version,
 * by which current code was generated are printed out to the terminal output.
 * If @b vp is not null, then it is set to the address with version info.
 * No terminal printout is performed in this case.
 *
 * @return current driver version number
 */
static int DisplayVersion(char **vp)
{
	static char vers_info_str[MAX_STR] =
		{ [0 ... sizeof(vers_info_str)-1] = 0 };


	if (!vers_info_str[0]) { /* not initialized yet */
		Cvorb_compile_date[11] = 0;
		Cvorb_compile_time [9] = 0;

		/* build-up version info string */
		ksprintf(vers_info_str, "Compiled on: %s %s."
			 " Generated by driverGen <%s> on [ %s ]",
			 Cvorb_compile_date, Cvorb_compile_time,
			 Cvorb_version, Cvorb_generation_time_str);
	}

	if (vp)
		*vp = vers_info_str;
	else
		kkprintf("\nCVORB Driver <Vers. %d>\n%s",
			 CVORB_DRVR_CURRENT_VERSION,
			 vers_info_str);

	return CVORB_DRVR_CURRENT_VERSION;
}

#ifdef __Lynx__

/**
 * @brief Calibration for timing measurements
 *
 * @param info -- dev info table
 *
 * Find out how much time does @e timing @e measurements algorithm itself
 * takes. This time inaccuracy will be taken into account during timing
 * measurements computation. Consider it like timing collibration mechanism.
 *
 * For Linux - calibration is always zero.
 *
 * @return rough estimation for timing measurement in nanoseconds for Lynx
 * @return 0 - in case of Linux
 */
static unsigned int CalibrateTime(DevInfo_t *info)
{
	int cntr;
	unsigned int nsS, nsF, calVal; /* ns */
	unsigned long sS, sF;	         /* s */
	unsigned long long sum = 0;

	/* 100 sampling */
	for (cntr = 0; cntr < 0x64; cntr++) {
		/* hope that is less then 4s (if no - then you are fucked!) */
		nsS = nanotime(&sS);
		nsF = nanotime(&sF);
		calVal = ((sF-sS) && nsF < nsS) ? nsF + 1000000000 - nsS :
			nsF - nsS;
		sum += calVal;
	}

	calVal = sum/0x64;
	return calVal;
}

#else  /* __linux__ */

/* form kernel/lib/div64.c */
uint32_t __attribute__((weak)) __div64_32(uint64_t *n, uint32_t base)
{
	uint64_t rem = *n;
	uint64_t b = base;
	uint64_t res, d = 1;
	uint32_t high = rem >> 32;

	/* Reduce the thing a bit first */
	res = 0;
	if (high >= base) {
		high /= base;
		res = (uint64_t) high << 32;
		rem -= (uint64_t) (high*base) << 32;
	}

	while ((int64_t)b > 0 && b < rem) {
		b = b+b;
		d = d+d;
	}

	do {
		if (rem >= b) {
			rem -= b;
			res += d;
		}
		b >>= 1;
		d >>= 1;
	} while (d);

	*n = res;
	return rem;
}

#endif


/**
 * @brief Process timing data, that was measured during driver code execution.
 *
 * @param tStr   -- measured time in %E format
 *
 * As currently @e LynxOS doesn't support %E output format, time string in
 * seconds (%E) representation is build-up and store in @e tStr parameter.
 * Note, that accuracy is limited up to 4 sec MAX. So if exec time is more,
 * than buildup string will contain notification message saying, that time is
 * more then 4 secs.
 *
 * @return Computed time in ns, @b LIMITED up to 4s (i.e. 4E+9ns) If time
 *         exeeds 4s, then -1 (i.e. 0xffffffff) is returnded. @e tStr string
 *         is set to the measured time in sec (%E format), or if it exeeds 4
 *         sec, then string will contain appropriate message.
 */
static unsigned int ComputeTime(char tStr[TSTR_LEN])
{
	int tseCntr, power;
	unsigned int  execTN = 0; /* total execution time in ns */
	unsigned long execTS = 0; /* total execution time in sec */

	static int e[10] = { /* all possible exp values */
		1,	   /* s  */
		10,	   /* ms */
		100,	   /* ms */
		1000,	   /* ms */
		10000,	   /* us */
		100000,	   /* us */
		1000000,   /* us */
		10000000,  /* ns */
		100000000, /* ns */
		1000000000 /* ns */
	};

	/* finish time measurements */
#ifdef __Lynx__
	GlobEndN = nanotime(&GlobEndS);
	execTS = GlobEndS - GlobStartS; /* total exec time in seconds */
#else
	getnstimeofday(&_t_end);
	_t_delta = timespec_sub(_t_end, _t_beg);
	_ac_etime = timespec_to_ns(&_t_delta);
	execTN = __div64_32(&_ac_etime, e[9]);
	execTS = _ac_etime;
#endif

	/* exec time is more or equal 4 sec. printout and return */
	if (execTS >= 4) {
		ksprintf(tStr, "> 4.00000E+00s");
		return -1;
	}

	/* init time string */
	bzero(tStr, sizeof(tStr));

	/* printout in XXs XXns format */
	/*
	cprintf("\nDone in %ds %dns.\n",
		execTS, (execTS && GlobEndN < GlobStartN) ?
		GlobEndN + e[9] - GlobStartN : GlobEndN - GlobStartN);
	*/

	/* convert seconds to nanoseconds */
	execTS *= e[9];

#ifdef __Lynx__
	/* compute total exec time in nanosec */
	execTN = execTS + GlobEndN - GlobStartN - GlobCalVal;
#else
	execTN += execTS;
#endif

	/* get current time dimension */
	for (power = 9; power >= 0; power--)
		if (execTN/e[power])/* we've got our dimension */
			break;

	/* build-up time string tail. precision will be */
	/* limited to 5 digits after the decimal point  */
	ksprintf(tStr, "%u", execTN);
	for (tseCntr = power; tseCntr >= 1; tseCntr--)
		/* shift one position to the right */
		tStr[tseCntr+1] = tStr[tseCntr];
	tStr[1] = '.';
	tStr[7] = 'E';
	tStr[8] = (9-power) ? '-' : '+';
	ksprintf(&tStr[9], "%02ds", 9-power);
	return execTN;
}


/* Standart getting/setting register operations for CVORB module
   are located in included file */
#include "CvorbGetSetReg.inc.c"


/**
 * @brief Entry point function. Initializes minor devices.
 *
 * @param statPtr -- statics table pointer
 * @param devno   -- contains major/minor dev numbers
 * @param flp     -- file pointer
 *
 * @return OK     -- if succeed.
 * @return SYSERR -- in case of failure.
 */
int Cvorb_open(register CVORBStatics_t *statPtr,
		     int devno, struct file *flp)
{
	int minN = minor(devno); /* get minor device number */
	int proceed;	/* if standard code execution should be
			   proceed after call to
			   user entry point function  */
	int usrcoco;	/* completion code of user entry point function */

	if (minN >= CVORB_MAX_NUM_CARDS) {
		kkprintf("%sMinor number (%d) exceeds MAX allowed"
			 " cards number (%d)\n",
			 ERR_MSG, minN, CVORB_MAX_NUM_CARDS);
		pseterr(ENXIO);
		return SYSERR; /* -1 */
	}

	kkprintf("Cvorb: Open Logical Unit %d.\n", statPtr->info->mlun);

	/* user entry point function call */
	usrcoco = CvorbUserOpen(&proceed, statPtr, devno, flp);
	if (!proceed) /* all done by user */
		return usrcoco;

	kkprintf("Cvorb: Done\n\n");

	return OK; /* 0 */
}


/**
 * @brief Entry point function.Called to close open file descriptor.
 *
 * @param statPtr -- statics table pointer
 * @param flp     -- file pointer. Lynx/Linux specific.
 *                   See (sys/file.h) for Lynx and (linux/fs.h) for Linux.
 *
 * @return OK     - if succeed.
 * @return SYSERR - in case of failure.
 */
int Cvorb_close(register CVORBStatics_t *statPtr, struct file *flp)
{
	int minN;    /* minor device number */
	int proceed; /* if standard code execution should be proceed
			after call to user entry point function  */
	int usrcoco; /* completion code of user entry point function */

#ifdef __Lynx__
	minN = minor(flp->dev);
#else
	minN = iminor(flp->f_path.dentry->d_inode);
#endif

	/* user entry point function call */
	usrcoco = CvorbUserClose(&proceed, statPtr, flp);
	if (!proceed) /* all done by user */
		return usrcoco;

	return OK; /* 0 */
}


/**
 * @brief Entry point function. Reads data from the device.
 *
 * @param statPtr -- statics table pointer
 * @param flp     -- file pointer
 * @param buff    -- character buffer pointer
 * @param count   -- number of bytes to copy
 *
 * @return number of bytes actually copied, including zero - if succeed.
 * @return SYSERR                                          - if fails.
 */
int Cvorb_read(register CVORBStatics_t *statPtr,
		     struct file *flp, char *buff, int count)
{
	int minN;    /* minor device number */
	int proceed; /* if standard code execution should be proceed
			after call to user entry point function  */
	int usrcoco; /* completion code of user entry point function */

#ifdef __Lynx__
	minN = minor(flp->dev);
#else
	minN = iminor(flp->f_path.dentry->d_inode);
#endif

	/* user entry point function call */
	usrcoco = CvorbUserRead(&proceed, statPtr, flp, buff, count);
	if (!proceed) /* all done by user */
		return usrcoco;

	return usrcoco; /* number of read bytes */
}


/**
 * @brief Entry point function. Sends data to the device.
 *
 * @param statPtr -- statics table pointer
 * @param flp     -- file pointer. Lynx/Linux specific.
 *                   See (sys/file.h) for Lynx and (linux/fs.h) for Linux.
 * @param which   -- condition to monitor. Not valid in case of Linux!\n
 * @param buff    -- char buffer pointer
 * @param count   -- the number of bytes to copy
 *
 * @return number of bytes actually copied, including zero - if succeed.
 * @return SYSERR                                          - if fails.
 */
int Cvorb_write(register CVORBStatics_t *statPtr,
		      struct file *flp, char *buff, int count)
{
	int minN; /* minor device number */
	int proceed;	/* if standard code execution should be proceed after
			   call to user entry point function  */
	int usrcoco;	/* completion code of user entry point function */

#ifdef __Lynx__
	minN = minor(flp->dev);
#else  /* __linux__ */
	minN = iminor(flp->f_path.dentry->d_inode);
#endif

	/* user entry point function call */
	usrcoco = CvorbUserWrite(&proceed, statPtr, flp, buff, count);
	if (!proceed) /* all done by user */
		return usrcoco;

	return usrcoco; /* number of written bytes */
}


/**
 * @brief Entry point function. Supports I/O polling or multiplexing.
 *
 * @param statPtr -- statics table pointer
 * @param flp     -- file pointer. Lynx/Linux specific.
 *                   See (sys/file.h) for Lynx and (linux/fs.h) for Linux.
 * @param which   -- condition to monitor. Not valid in case of Linux!\n
 *                   <b> SREAD, SWRITE, SEXCEPT </b> in case of Lynx.
 * @param ffs     -- select data structure in case of Lynx.\n
 *                   struct poll_table_struct in case of Linux.
 *
 * @return OK     - if succeed.
 * @return SYSERR - in case of failure.
 */
int Cvorb_select(register CVORBStatics_t *statPtr,
		       struct file *flp, int which, struct sel *ffs)
{
	int minN;    /* minor device number */
	int proceed; /* if standard code execution should be proceed after
			call to user entry point function  */
	int usrcc; /* completion code of user entry point function */

#ifdef __Lynx__
	minN = minor(flp->dev);
#else  /* __linux__ */
	minN = iminor(flp->f_path.dentry->d_inode);
#endif

	/* user entry point function call */
	usrcc = CvorbUserSelect(&proceed, statPtr, flp, which, ffs);
	if (!proceed) /* all done by user */
		return usrcc;

	return OK; /* 0 */
}


/**
 * @brief CVORB ioctl entry point
 *
 * @param s   -- statics table
 * @param f   -- file pointer. Lynx/Linux specific.
 *               See (sys/file.h) for Lynx and (linux/fs.h) for Linux.
 * @param com -- ioctl number
 * @param arg -- arguments
 *
 * By default - we do check r/w bounds while accessing the register.
 *
 * @return OK     - if succeed.
 * @return SYSERR - in case of failure.
 */
int Cvorb_ioctl(register CVORBStatics_t *s,
		      struct file *f, int com, char *arg)
{
	static int c_rwb = 1; /* check r/w bounds (1 - yes, 0 - no)
				 Valid _ONLY_ for Lynx! */
	int minN;     /* minor device number (LUN) */
	int proceed;  /* if standard code execution should be proceed after
			 call to user entry point function  */
	int usrcoco;  /* completion code of user entry point function */
	int r_rw = 0; /* repetitive r/w (1 - yes, 0 - no) */

	START_TIME_STAT(); /* timing measurements */

#ifdef __Lynx__
	minN = minor(f->dev);
#else
	minN = iminor(f->f_path.dentry->d_inode);
#endif

	/* user entry point function call */
	usrcoco = CvorbUserIoctl(&proceed, s, f, minN, com, arg);
	if (!proceed) /* all done by user */
		return usrcoco;

 rep_ioctl:
	switch (com) { /* default 'ioctl' driver operations */
	case SRV_GET_DEBUG_FLAG:
		return get___SRV__DEBUG_FLAG(s, arg, c_rwb, r_rw);
		break;
	case SRV_SET_DEBUG_FLAG:
		return set___SRV__DEBUG_FLAG(s, arg, c_rwb, r_rw);
		break;
	case SRV_GET_DEVINFO_T:
		return get___SRV__DEVINFO_T(s, arg, c_rwb, r_rw);
		break;
	case SRV_GET_DRVR_VERS:
		return get___SRV__DRVR_VERS(s, arg, c_rwb, r_rw);
		break;
	case SRV_GET_DAL_CONSISTENT:
		return get___SRV__DAL_CONSISTENT(s, arg, c_rwb, r_rw);
		break;
	case SRV__REP_REG_RW:
		return srv_func___SRV__REP_REG_RW(s, arg, c_rwb, r_rw);
		break;
	case SRV__RW_BOUNDS:
		return srv_func___SRV__RW_BOUNDS(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_INT_SRC:
		return get_INT_SRC(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_INT_EN:
		return get_INT_EN(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_INT_EN:
		return set_INT_EN(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_INT_L:
		return get_INT_L(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_INT_L:
		return set_INT_L(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_INT_V:
		return get_INT_V(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_INT_V:
		return set_INT_V(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_VHDL_V:
		return get_VHDL_V(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_PCB_SN_H:
		return get_PCB_SN_H(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_PCB_SN_L:
		return get_PCB_SN_L(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_TEMP:
		return get_TEMP(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_ADC:
		return get_ADC(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_HISTORY_SOFT_PULSE:
		return get_wo_SOFT_PULSE(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_SOFT_PULSE:
		return set_SOFT_PULSE(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_EXT_CLK_FREQ:
		return get_EXT_CLK_FREQ(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_CLK_GEN_CNTL:
		return get_CLK_GEN_CNTL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_CLK_GEN_CNTL:
		return set_CLK_GEN_CNTL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_MOD_STAT:
		return get_MOD_STAT(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_MOD_CFG:
		return get_MOD_CFG(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_MOD_CFG:
		return set_MOD_CFG(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_DAC_VAL:
		return get_DAC_VAL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_DAC_VAL:
		return set_DAC_VAL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_SRAM_SA:
		return get_SRAM_SA(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_SRAM_SA:
		return set_SRAM_SA(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_SRAM_DATA:
		return get_SRAM_DATA(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_SRAM_DATA:
		return set_SRAM_DATA(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_DAC_CNTL:
		return get_DAC_CNTL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_DAC_CNTL:
		return set_DAC_CNTL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_CH_STAT:
		return get_CH_STAT(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_CH_CFG:
		return get_CH_CFG(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_CH_CFG:
		return set_CH_CFG(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_FUNC_SEL:
		return get_FUNC_SEL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_FUNC_SEL:
		return set_FUNC_SEL(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_FCT_EM_H:
		return get_FCT_EM_H(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_FCT_EM_H:
		return set_FCT_EM_H(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_FCT_EM_L:
		return get_FCT_EM_L(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_FCT_EM_L:
		return set_FCT_EM_L(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_SLOPE:
		return get_SLOPE(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_SLOPE:
		return set_SLOPE(s, arg, c_rwb, r_rw);
		break;
	case CVORB_GET_CH_REC_CYC:
		return get_CH_REC_CYC(s, arg, c_rwb, r_rw);
		break;
	case CVORB_SET_CH_REC_CYC:
		return set_CH_REC_CYC(s, arg, c_rwb, r_rw);
		break;
	default:
		pseterr(EINVAL);
		return SYSERR; /* -1 */
	} /* end of 'ioctl' operations switch */

	return OK; /* 0 */
}


/**
 * @brief Cleanup and deallocation of the Driver statics table.
 *
 * @param statPtr - deallocate this
 *
 * @return void
 */
static void CvorbMemCleanup(CVORBStatics_t *statPtr)
{
  DevInfo_t *dip = statPtr->info; /* device info pointer */

  if (statPtr->card != NULL) {
    kkprintf("Cvorb: Cleaning up Logical Unit %d\n", dip->mlun);

    if (statPtr->card->wo != NULL) {
      kkprintf("Cvorb: Writeonly structure deallocation - ");
      sysfree((char*)statPtr->card->wo, (long)sizeof(CVORBWriteonly_t));
      kkprintf("OK\n");
    }

    if (statPtr->card->ex != NULL) {
      kkprintf("Cvorb: Extraneous structure deallocation - ");
      sysfree((char*)statPtr->card->ex, (long)sizeof(CVORBExtraneous_t));
      kkprintf("OK\n");
    }
    kkprintf("Cvorb: Topology structure deallocation - ");
    sysfree((char*)statPtr->card, (long)sizeof(CVORBTopology_t));
    kkprintf("OK\n");

    kkprintf("Cvorb: All Logical Unit specific resources have been deallocated.\n");
  }

  if (statPtr->usrst != NULL) {
    kkprintf("Cvorb: User-defined statics data table deallocation - ");
    sysfree((char*)statPtr->usrst, (long)sizeof(CVORBUserStatics_t));
    kkprintf("OK\n");
  }

  kkprintf("Cvorb: Device info table structure deallocation - ");
  sysfree((char*)statPtr->info, (long)sizeof(DevInfo_t));
  kkprintf("OK\n");

  kkprintf("Cvorb: Statics structure deallocation - ");
  sysfree((char*)statPtr, (long)sizeof(CVORBStatics_t));
  kkprintf("OK\n");
}


/* to suppress implisit declaration warnings */
#ifdef __Lynx__
extern unsigned long find_controller _AP((unsigned long vmeaddr, unsigned long len, unsigned long am, unsigned long offset, unsigned long size, struct pdparam_master  *param));
#endif

/**
 * @brief Free mapped VME resources
 *
 * @param dit -- info table
 *
 * @return  0 - on success
 * @return -1 - if fails
 */
int __attribute__((weak)) unmapVmeAddr(DevInfo_t *dit)
{
	int i, rc = 0;
	AddrInfo_t *aip = &dit->addr1;

	for (i = 0; i < ASA; i++) {
		if (aip->baseAddr != ADCG__NO_ADDRESS)
			if (return_controller(aip->baseAddr, aip->range))
				rc = -1;
		aip++;
	}

	return rc;
}

/*
 * In lynx, find_controller accepts 0 as @size as a way of avoiding the
 * test access after setting up the mapping. In Linux, however,
 * passing 0 as @size will always fail, since this parameter is in fact
 * the one that provides the data width for the whole mapping, and
 * will therefore be detected as invalid; We deal with this by taking
 * the data width from the mapping's description.
 */
#ifdef __linux__
static inline void check_datawidth(unsigned long *data_width, AddrInfo_t *map)
{
	if (!*data_width)
		*data_width = map->dpSize / 8;
}
#else
static inline void check_datawidth(unsigned long *data_width, AddrInfo_t *map)
{
}
#endif /* __linux__ */

/**
 * @brief Maps VME address space into PCI address space.
 *
 * @param info     -- dev info table
 * @param map	   -- mapping descriptor
 * @param err      -- error number will go here in case of error
 *
 * @return -1			 - if FAILS.
 * @return mapped device address - if SUCCEED.
 */
static kaddr_t MapVMEaddress(DevInfo_t *info, AddrInfo_t *map, int *err)

{
	struct pdparam_master param; /* CES structure containing VME access
					parameters */
	int		offst = 0;  /* check address offset */
	unsigned long	size  = 0;  /* size in bytes of read-test zone
				       (0 to disable read test). If more
				       than 4 bytes, then value will be >> 2
				       and obtained number of elements
				       (4 bytes each) will be read from
				       memory */
	kaddr_t k_addr;  /*  */
	kaddr_t		infoBase	= map->baseAddr;
	unsigned long	len		= map->range;
	vmeam_t		am		= map->addrModif;

	/* Compute address in system space */
	/* CES: build an address window (64 kbyte) for
	   VME A16-D16 or A24-D32 or A32-D32 A24-D08 accesses
	   (depend on config) */
	memset(&param, 0, sizeof(param)); /* safety zeroing */
	param.iack   = 1; /* VME iack. 0: IACK pages, 1: not IACK pages */
	param.rdpref = 0; /* VME read prefetch option. 0: disable, 1: enable */
	param.wrpost = 0; /* VME write posting option. 0: disable, 1: enable */
	param.swap   = SINGLE_AUTO_SWAP; /* VME swap option: one of
					    SINGLE_NO_SWAP,
					    SINGLE_AUTO_SWAP,
					    SINGLE_WORD_SWAP,
					    SINGLE_BYTEWORD_SWAP */
	param.sgmin  = 0;  /* reserved, _must_ be 0  */
	param.dum[0] = VME_PG_SHARED; /* page qualifier (shared/private)
					 In this case - window is sharable */
	param.dum[1] = 0;             /* XPC ADP-type on RIO3 */
	param.dum[2] = 0;             /* reserved, _must_ be 0 */

	/* check VME Address Modifier code */
	switch (am) {
	case DG_AM_SH: /* short    */
	case DG_AM_ST: /* standard */
	case DG_AM_EX: /* extended */
	case DG_AM_CR: /* Configuration Register */
		break; /* we cool */
	default:
		kkprintf("%sUNKNOWN address modifier (%d)", ERR_MSG, am);
		*err = EINVAL;
		return -1;
	}

	/* module checking will be performed */
	if (info->chrindex != -1) {
		offst = info->regDesc[info->chrindex].regOffset;
		size  = info->regDesc[info->chrindex].regSize;
	}

	if (info->debugFlag & DBGINSTL) {
		kkprintf("\nfind_controller() call parameters are:\n");
		kkprintf("+--------------------------------------\n");
		kkprintf("| Base Addr  => 0x%x\n", infoBase);
		kkprintf("| Addr Range => 0x%lx\n", len);
		kkprintf("| Addr Modifier => '%s' (0x%x)\n",
			 (am == DG_AM_SH)?"SHort":(am == DG_AM_ST)?"STandard":
			 (am == DG_AM_EX)?"EXtended":(am == DG_AM_CR)?
			 "Configuration Register":"UNKNOWN", am);
		if (info->chrindex == -1)
			kkprintf("| Module checking will NOT be performed!\n");
		else {
			kkprintf("| Offset from VME Base Address at which a"
				 " read test will be made is 0x%x bytes.\n",
				 offst);
			kkprintf("| Size of read-test zone is %ld bytes"
				 " long.\n", size);
		}
		kkprintf("+--------------------------------------\n\n");
	}

	/*
	 * the behaviour of @size in find_controller differs
	 * among platforms: make sure anything blows up
	 */
	check_datawidth(&size, map);

	if (info->debugFlag & DBGINSTL)
		kkprintf("find_controller() call - ");
	k_addr = find_controller((u_long)infoBase, len, am, offst, size,
				 &param);
	if (k_addr == -1) {	/* error */
		if (info->debugFlag & DBGINSTL) {
			kkprintf("FAILED.\n");
			kkprintf("  (VME device @0x%x. Address range is"
				 " 0x%lx bytes.)\n", infoBase, len);
		}
		*err = ENXIO;
		return -1;
	}

	if (info->debugFlag & DBGINSTL) {
		kkprintf("OK.\n");
		kkprintf("  (VME device @0x%x has been mapped @0x%x)\n",
			 infoBase, k_addr);
	}
	return k_addr;
}


/**
 * @brief Maps specified part of the VME address space into PCI address space.
 *
 * @param info -- complete device information
 *
 * Also checks if device is installed in the crate by means of reading at given
 * address. If read test address is not provided -  then @b no module checking
 * will be perfomed. If there is no base address (i.e. address is
 * ADCG__NO_ADDRESS), then no mapping and no module checking will be performed.
 *
 * @return -errno - some negative value, if address mapping fails
 * @return 1, 2   - i.e. number of mapped addresses in case of success
 */
static int MapAndCheckDevice(DevInfo_t *info)
{
	kaddr_t mapped_addr; /* mapped address */
	int		cntr;
	AddrInfo_t	*aitptr;
	int		res = 0;

	if (info->debugFlag & DBGINSTL) {
		kkprintf("\n\n%s() parameters are:\n", __FUNCTION__);
		kkprintf("+-----------------------------------\n");
		if (info->addr1.baseAddr != ADCG__NO_ADDRESS)
			kkprintf("| addr1 => 0x%x\n", info->addr1.baseAddr);
		else
			kkprintf("| addr1 => NOT defined.\n");

		if (info->addr2.baseAddr != ADCG__NO_ADDRESS)
			kkprintf("| addr2 => 0x%x\n", info->addr2.baseAddr);
		else
			kkprintf("| addr2 => NOT defined.\n");

		for (cntr = 0; cntr < info->blkAmount; cntr++)
			kkprintf("| Block %02d offset: 0x%lx\n",
				 cntr, info->blkDesc[cntr].offset);
		kkprintf("+-----------------------------------\n\n");
	}

	aitptr = &(info->addr1);	/* init pointer */
	for (cntr = 0; cntr < ASA; cntr++) {
		/* move through all address spaces */
		if (aitptr->baseAddr != ADCG__NO_ADDRESS) {
			mapped_addr = MapVMEaddress(info, aitptr, &res);
			if (mapped_addr != -1) {
				/* overwrite with mapped base address */
				aitptr->baseAddr = mapped_addr;
				if (info->debugFlag & DBGINSTL)
					kkprintf("  addr%1d succesfully"
						 " mapped.\n", cntr+1);
				res++; /* increase counter */
			} else {
				if (info->debugFlag & DBGINSTL)
					kkprintf("  addr%1d mapping fails!"
						 " (errcode is %d)\n",
						 cntr+1, res);
				res *= -1;
			}
		}
		aitptr++; /* move pointer to the next addr space */
	}

	return res;
}


/**
 * @brief Entry point function.
 *
 * @param info --
 *
 * Initializes the hardware and allocates shared memory buffers. Invoked each
 * time the device driver is installed for a major device (i.e. each time
 * when @b cdv_install() or @b bdv_install() functions are called).
 *
 * @return pointer to a statics data structure - if succeed.
 * @return SYSERR                              - in case of failure.
 */
#define INST_OK()						\
do {								\
  kkprintf("Cvorb: Driver (LUN %d) ", info->mlun);	\
  kkprintf(" installation Complete. ");				\
  DisplayVersion(NULL);						\
  kkprintf("\n\n");						\
} while (0)

#define INST_FAIL()						\
do {								\
  kkprintf("Cvorb: Driver (LUN %d) ", info->mlun);	\
  kkprintf(" installation Fails. ");				\
  DisplayVersion(NULL);						\
  kkprintf("\n\n");						\
} while (0)

char* Cvorb_install(void *infofile)
{
	register CVORBStatics_t *statPtr;
	char *usrcoco; /* completion code of user entry point function */
	int cntr;
	AddrInfo_t *aiptr;
	DevInfo_t *info;
	int res __attribute__((unused));

	kkprintf("Cvorb: Device info table structure allocation - ");
	info = (DevInfo_t *)sysbrk(sizeof(DevInfo_t));
	if (!info) {
		/* Horrible failure */
		kkprintf("FAILED\n");
		pseterr(ENOMEM);
		INST_FAIL();
		return (char *)SYSERR; /* -1 */
	}
	kkprintf("OK\n");

	kkprintf("Cvorb: Copying info table from user space - ");
	memcpy(info, infofile, sizeof(DevInfo_t));
	kkprintf("OK\n");


  if (info->debugFlag & DBGINSTL) {	/* only in case of debugging */
    aiptr = &(info->addr1);
    kkprintf("\n\nDriver install procedure parameters are:\n");
    kkprintf("+-----------------------------------------\n");
    /* info about 2 address spaces */
    for (cntr = 0; cntr < 2; cntr++) {
      kkprintf("|    Addr%d info:\n", cntr+1);
      kkprintf("|    -----------\n");
      if (aiptr->baseAddr != ADCG__NO_ADDRESS) {
	kkprintf("|     Base address      => 0x%x\n", aiptr->baseAddr);
	kkprintf("|     Address range     => 0x%x\n", aiptr->range);
	kkprintf("|     Address increment => 0x%x\n", aiptr->increment);
	kkprintf("|     Dataport size     => %d\n", aiptr->dpSize);
	kkprintf("|     Address modifier  => %s (0x%x)\n|\n", (aiptr->addrModif == DG_AM_SH)?"SH":(aiptr->addrModif == DG_AM_ST)?"ST":(aiptr->addrModif == DG_AM_EX)?"EX":(aiptr->addrModif == DG_AM_CR)?"CR":"UNKNOWN", aiptr->addrModif);
      } else kkprintf("|     Addr%d NOT defined.\n|\n", cntr+1);
      aiptr++;
    }

    kkprintf("| Debug flag                 => 0x%x\n", info->debugFlag);
    kkprintf("| Opaque parameter           => '%s'\n", info->opaque);
    kkprintf("| Interrupt level            => %d\n", info->iLevel);
    kkprintf("| Interrupt vector           => %d\n", info->iVector);
    kkprintf("| Interrupt vector increment => %d\n", info->iVectorInc);
    kkprintf("| Number of channels         => %d\n", info->chan);
    kkprintf("+-----------------------------------------\n\n");

    if (info->debugFlag & DBGALLDI) {
      /* user wants really everything, so let him have it! */
      REGDESC *rdp = info->regDesc;
      BLKDESC *bdp = info->blkDesc;
      aiptr = &(info->addr1);

      /* 2 address space info */
      for (cntr = 0; cntr < 2; cntr++) {
	kkprintf("+-----------------------------\n");
	kkprintf("| Addr[%d].baseAddr  => 0x%X\n", cntr, aiptr->baseAddr);
	kkprintf("| Addr[%d].range     => 0x%X\n", cntr, aiptr->range);
	kkprintf("| Addr[%d].increment => 0x%X\n", cntr, aiptr->increment);
	kkprintf("| Addr[%d].dpSize    => 0x%d\n", cntr, aiptr->dpSize);
	kkprintf("| Addr[%d].addrModif => 0x%d\n", cntr, aiptr->addrModif);
	kkprintf("+-----------------------------\n\n");
	aiptr++;
      }

      /* general info */
      kkprintf("+-----------------------------\n");
      kkprintf("| 'mtn'        => %d\n",   info->mtn);
      kkprintf("| 'debugFlag'  => 0x%X\n", info->debugFlag);
      kkprintf("| 'opaque'     => '%s'\n", info->opaque);
      kkprintf("| 'iLevel'     => %d\n",   info->iLevel);
      kkprintf("| 'iVector'    => %d\n",   info->iVector);
      kkprintf("| 'iVectorInc' => %d\n",   info->iVectorInc);
      kkprintf("| 'chan'       => %d\n",   info->chan);
      kkprintf("| 'chrindex'   => %d\n",   info->chrindex);
      kkprintf("| 'gen_date'   => %ld\n",  info->gen_date);
      kkprintf("| 'dg_vers'    => '%s'\n", info->dg_vers);
      kkprintf("| 'regAmount'  => %d\n",   info->regAmount);
      kkprintf("| 'maxRegSz'   => %d\n",   info->maxRegSz);
      kkprintf("| 'checksum'   => %d\n",   info->checksum);
      kkprintf("+-----------------------------\n\n");

      /* all block info */
      for (cntr = 0; cntr < info->blkAmount; cntr++) {
	kkprintf("+---------------------------------------------\n");
	kkprintf("| Blk[%d] 'block'       => %d\n", cntr, bdp[cntr].block);
	kkprintf("| Blk[%d] 'blkBaseAddr' => %d\n", cntr,
		 bdp[cntr].blkBaseAddr);
	kkprintf("| Blk[%d] 'offset'      => 0x%lX\n", cntr, bdp[cntr].offset);
	kkprintf("| Blk[%d] 'blksz_drvr'  => %d\n", cntr, bdp[cntr].blksz_drvr);
	kkprintf("| Blk[%d] 'blksz_sim'   => %d\n", cntr, bdp[cntr].blksz_sim);
	kkprintf("| Blk[%d] 'reg_am'      => %d\n", cntr, bdp[cntr].reg_am);
	kkprintf("+---------------------------------------------\n\n");
      }

      /* all registers info */
      for (cntr = 0; cntr < info->regAmount; cntr++) {
	kkprintf("+---------------------------------------------\n");
	kkprintf("| Reg[%d] 'ID'           => %d\n", cntr, rdp[cntr].regId);
	kkprintf("| Reg[%d] 'regName'      => %s\n", cntr, rdp[cntr].regName);
	kkprintf("| Reg[%d] 'busType'      => %s\n", cntr, rdp[cntr].busType);
	kkprintf("| Reg[%d] 'regType'      => %s (%d)\n", cntr, (rdp[cntr].regType == RT_REAL)?"RT_REAL":(rdp[cntr].regType == RT_EXTR)?"RT_EXTR":"RT_SRVS", rdp[cntr].regType);
	kkprintf("| Reg[%d] 'regSize'      => %d\n", cntr, rdp[cntr].regSize);
	kkprintf("| Reg[%d] 'b_a'          => %s\n", cntr, rdp[cntr].b_a);
	kkprintf("| Reg[%d] 'bid'          => %d\n", cntr, rdp[cntr].bid);
	kkprintf("| Reg[%d] 'regOffset'    => 0x%X\n", cntr, rdp[cntr].regOffset);
	kkprintf("| Reg[%d] 'regDepth'     => %d\n", cntr, rdp[cntr].regDepth);
	kkprintf("| Reg[%d] 'regtl'        => %d\n", cntr, rdp[cntr].regtl);
	kkprintf("| Reg[%d] 'regar'        => %d\n", cntr, rdp[cntr].regar);
	kkprintf("| Reg[%d] 'rwIoctlOpNum' => 0x%x\n", cntr, rdp[cntr].rwIoctlOpNum);
	kkprintf("+---------------------------------------------\n\n");
      }
    }
  }

  kkprintf("Cvorb: Driver (LUN %d) installation begins...\n", info->mlun);

#ifdef __Lynx__
  GlobCalVal = CalibrateTime(info); /* do timing calibration */
  if (info->debugFlag & DBGTIMESTAT) /* time statistics is enabled */
     kkprintf("Cvorb: Calibrated timing is %dns per access.\n",
	      GlobCalVal);
#endif

  /*
     Should we disable interrupts here?
     int ps;
     disable(ps);
  */

	if (info->chrindex == -1)
		kkprintf("Cvorb: %sModule presence will NOT be"
			 " checked!\n", WARNING_MSG);
	else
		kkprintf("Cvorb: Module presence will be checked during"
			 " device address space mapping by reading '%s'"
			 " register @0x%x offset.\n",
			 info->regDesc[info->chrindex].regName,
			 info->regDesc[info->chrindex].regOffset);

	/* Check hardware module and abort installation if hardware not OK. */
	kkprintf("Cvorb: Mapping device address space - ");
	res = MapAndCheckDevice(info);
	if (res < 0) {
		kkprintf("FAILED\n");
		pseterr(res*(-1));	/* set error number for user */
		INST_FAIL();
		return (char*)SYSERR; /* -1 */
	} else if (res > 0) {
		kkprintf("OK\n");
	} else
		kkprintf("Nothing to map (no Addr1 and Addr2 defined)\n");

	/* For device driver resources, resource allocation must be done during
	   the installation routine (e.g.: decriptor of system call interface:
	   semaphore, system thread, etc.) */

	/* 0x0 */
	kkprintf("Cvorb: Statics data structure allocation - ");
	if(!(statPtr = (CVORBStatics_t*)
	     sysbrk((long)sizeof(CVORBStatics_t)))) {
		/* Horrible, impossible failure. */
		kkprintf("FAILED\n");
		pseterr(ENOMEM);
		INST_FAIL();
		return (char*)SYSERR; /* -1 */
	}
	kkprintf("OK\n");

	/* 0x1 */
	kkprintf("Cvorb: Hardware topology structure allocation - ");
	if( !(statPtr->card = (CVORBTopology_t*)
	      sysbrk((long)sizeof(CVORBTopology_t))) ) {
		/* Horrible, impossible failure. */
		kkprintf("FAILED\n");
		pseterr(ENOMEM);
		INST_FAIL();
		return (char*)SYSERR; /* -1 */
	}
	bzero((char*)statPtr->card, sizeof(CVORBTopology_t));
	kkprintf("OK\n");

	/* 0x2 */
	if (sizeof(CVORBWriteonly_t) > 0) {
		kkprintf("Cvorb: Writeonly structure allocation - ");
		if ( !(statPtr->card->wo = (CVORBWriteonly_t*)
		       sysbrk((long)sizeof(CVORBWriteonly_t))) ) {
			/* Horrible, impossible failure. */
			kkprintf("FAILED\n");
			pseterr(ENOMEM);
			INST_FAIL();
			return (char*)SYSERR;	/* -1 */
		}
		bzero((char*)statPtr->card->wo, sizeof(CVORBWriteonly_t));
		kkprintf("OK\n");
	} else {
		statPtr->card->wo = NULL;
	}

	/* 0x3 */
	if (sizeof(CVORBExtraneous_t) > 0) {
		kkprintf("Cvorb: Extraneous structure allocation - ");
		if ( !(statPtr->card->ex = (CVORBExtraneous_t*)
		       sysbrk((long)sizeof(CVORBExtraneous_t))) ) {
			/* Horrible, impossible failure. */
			kkprintf("FAILED\n");
			pseterr(ENOMEM);
			INST_FAIL();
			return (char*)SYSERR;	/* -1 */
		}
		bzero((char*)statPtr->card->ex, sizeof(CVORBExtraneous_t));
		kkprintf("OK\n");
	} else {
		statPtr->card->ex = NULL;
	}

	/* 0x4 */
	kkprintf("Cvorb: Block 0 assignment ");
	statPtr->card->block00 =
	(CVORBBlock00_t*)(info->addr1.baseAddr +
					info->blkDesc[0].offset);
	kkprintf("[to mapped addr 0x%x] - OK\n",
		 (int)statPtr->card->block00);

	kkprintf("Cvorb: Block 1 assignment ");
	statPtr->card->block01 =
	(CVORBBlock01_t*)(info->addr1.baseAddr +
					info->blkDesc[1].offset);
	kkprintf("[to mapped addr 0x%x] - OK\n",
		 (int)statPtr->card->block01);

	/* 0x5 save info table pointer */
	statPtr->info = (void*)info;

	/* 0x6 */
	if (sizeof(CVORBUserStatics_t) > 0) { /* only if it's not empty */
		kkprintf("Cvorb: User-defined statics data table"
			 " allocation - ");
		if( !(statPtr->usrst = (CVORBUserStatics_t*)
		      sysbrk( (long)sizeof(CVORBUserStatics_t) )) ) {
			/* Horrible, impossible failure. */
			kkprintf("FAILED\n");
			pseterr(ENOMEM);
			INST_FAIL();
			return (char*)SYSERR; /* -1 */
		}
		bzero((char*)statPtr->usrst, sizeof(CVORBUserStatics_t));
		kkprintf("OK\n");
	} else {
		statPtr->usrst = NULL;
	}

	/* user entry point function call */
	usrcoco = CvorbUserInst(NULL, info, statPtr);
	if (usrcoco == (char*)SYSERR ) {
		INST_FAIL();
		CvorbMemCleanup(statPtr); /* free allocated memory */
		return (char*)SYSERR; /* -1 */
	}

	INST_OK();
	return (char*)statPtr;
}


/**
 * @brief Driver uninstallation.
 *
 * @param statPtr -- statics table
 *
 * Deallocates shared memory and clears used interrupt vectors.
 *
 * @return OK     - if succeed.
 * @return SYSERR - in case of failure.
 */
int Cvorb_uninstall(CVORBStatics_t *statPtr)
{
	int rc;

	/*
	  Should we disable interrupts?
	  int ps;
	  disable(ps);
	*/

	kkprintf("Cvorb: Uninstall...\n");

	/* user entry point function call */
	rc = CvorbUserUnInst(NULL, statPtr);
	if (rc == SYSERR )
		return rc; /* -1 */

	/* Free mapped resources (if any) */
	unmapVmeAddr(statPtr->info);

	/* cleanup and release statics table */
	CvorbMemCleanup(statPtr);

	/*
	  Enable interrupts.
	  restore(ps);
	*/

	kkprintf("Cvorb: Done\n\n");

	return OK;
}

/* CVORB entry points */
#ifdef __linux__
struct dldd entry_points = {
	(int(*)(void*, int, struct cdcm_file*))
	/* open      */ Cvorb_open,
	 (int(*)(void*, struct cdcm_file*))
	/* close     */ Cvorb_close,
	 (int(*)(void*, struct cdcm_file*, char*, int))
	/* read      */ Cvorb_read,
	 (int(*)(void*, struct cdcm_file*, char*, int))
	/* write     */ Cvorb_write,
	 (int(*)(void*, struct cdcm_file*, int, struct cdcm_sel*))
	/* select    */ Cvorb_select,
	 (int(*)(void*, struct cdcm_file*, int, char*))
	/* ioctl     */ Cvorb_ioctl,
	 (char* (*)(void*))
	/* install   */ Cvorb_install,
	 (int(*)(void*))
	/* uninstall */ Cvorb_uninstall,
	/* memory-mapped devices access */ NULL
};
#else
struct dldd entry_points = {
  /* open      */ Cvorb_open,
  /* close     */ Cvorb_close,
  /* read      */ Cvorb_read,
  /* write     */ Cvorb_write,
  /* select    */ Cvorb_select,
  /* ioctl     */ Cvorb_ioctl,
  /* install   */ Cvorb_install,
  /* uninstall */ Cvorb_uninstall,
  /* memory-mapped devices access */ NULL
};
#endif

