###############################################################################
# @file Makefile
#
# @brief Cvorb driver framework compilation
#
# Automatically generated by driver-gen
#
# @author Copyright (C) 2003-2010 CERN. Yury GEORGIEVSKIY <ygeorgie@cern.ch>
#
# @date Created on 29/06/2009
#
# @section license_sec License
#          Released under the GPL
###############################################################################

# Standart driver directory tree
SUBDIRS = \
	lib \
	driver \
	test \
	include \
	install

include ./Makefile.base