.TH "libctr" 3 "14 May 2012" "libctr Timing Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
libctr \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
to replace timlib 
.PP
\fBAuthor:\fP
.RS 4
Julian Lewis BE/CO/HT Julian Lewis 
.RE
.PP
\fBVersion:\fP
.RS 4
Mon 14th May 2012 
.RE
.PP

.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for libctr Timing Library from the source code.
