.TH "TimLibCstBlock" 3 "12 Nov 2008" "Low Level Timing Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimLibCstBlock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBValid\fP"
.br
.ti -1c
.RI "\fBTimLibCstStat\fP \fBStat\fP"
.br
.ti -1c
.RI "unsigned long \fBIdMSL\fP"
.br
.ti -1c
.RI "unsigned long \fBIdLSL\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Card Status and ID block 
.PP
.SH "Member Data Documentation"
.PP 
.SS "unsigned long \fBTimLibCstBlock::IdLSL\fP"
.PP
.SS "unsigned long \fBTimLibCstBlock::IdMSL\fP"
.PP
.SS "\fBTimLibCstStat\fP \fBTimLibCstBlock::Stat\fP"
.PP
.SS "unsigned long \fBTimLibCstBlock::Valid\fP"
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Low Level Timing Library from the source code.
