.TH "TimLibExtBlock" 3 "12 Nov 2008" "Low Level Timing Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimLibExtBlock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBValid\fP"
.br
.ti -1c
.RI "unsigned long \fBPllErrThresh\fP"
.br
.ti -1c
.RI "unsigned long \fBPllDacLowPass\fP"
.br
.ti -1c
.RI "unsigned long \fBPllDacCIConst\fP"
.br
.ti -1c
.RI "unsigned long \fBPllMonCIConst\fP"
.br
.ti -1c
.RI "unsigned long \fBPllPhaseDCM\fP"
.br
.ti -1c
.RI "unsigned long \fBPllUtcPhasErr\fP"
.br
.ti -1c
.RI "unsigned long \fBTemperature\fP"
.br
.ti -1c
.RI "unsigned long \fBMsMissed\fP"
.br
.ti -1c
.RI "\fBTimLibTime\fP \fBMsLastErr\fP"
.br
.ti -1c
.RI "unsigned long \fBPllErrCount\fP"
.br
.ti -1c
.RI "\fBTimLibTime\fP \fBPllLastErr\fP"
.br
.ti -1c
.RI "unsigned long \fBFrmMissed\fP"
.br
.ti -1c
.RI "\fBTimLibTime\fP \fBFrmMissedLast\fP"
.br
.ti -1c
.RI "unsigned long \fBRecBadCycles\fP"
.br
.ti -1c
.RI "unsigned long \fBRecRcvdFrms\fP"
.br
.ti -1c
.RI "unsigned long \fBRecSentFrms\fP"
.br
.ti -1c
.RI "unsigned long \fBPllUtcErrs\fP"
.br
.ti -1c
.RI "\fBTimLibTime\fP \fBStartOne\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Extended memory diagnostics block 
.PP
.SH "Member Data Documentation"
.PP 
.SS "unsigned long \fBTimLibExtBlock::FrmMissed\fP"
.PP
Number of missed timing frames 
.SS "\fBTimLibTime\fP \fBTimLibExtBlock::FrmMissedLast\fP"
.PP
Time when last frame was missed 
.SS "\fBTimLibTime\fP \fBTimLibExtBlock::MsLastErr\fP"
.PP
Time last MS was missed 
.SS "unsigned long \fBTimLibExtBlock::MsMissed\fP"
.PP
Number of millisencods missed since last power up 
.SS "unsigned long \fBTimLibExtBlock::PllDacCIConst\fP"
.PP
Log2 of number avarages DAC Value CIC low pass filter 
.SS "unsigned long \fBTimLibExtBlock::PllDacLowPass\fP"
.PP
Low Passed DAC value used when no GMT (CIC filter) 
.SS "unsigned long \fBTimLibExtBlock::PllErrCount\fP"
.PP
Number of pll errors since last power up (past threshold) 
.SS "unsigned long \fBTimLibExtBlock::PllErrThresh\fP"
.PP
Pll error threshold to generate an error 
.SS "\fBTimLibTime\fP \fBTimLibExtBlock::PllLastErr\fP"
.PP
Time of last PLL error 
.SS "unsigned long \fBTimLibExtBlock::PllMonCIConst\fP"
.PP
Log2 of interrupt reduction factor (averages over this) 
.SS "unsigned long \fBTimLibExtBlock::PllPhaseDCM\fP"
.PP
(Not used yet) Phase of the spartan DLL. 
.SS "unsigned long \fBTimLibExtBlock::PllUtcErrs\fP"
.PP
Number of UTC PLL errors 
.SS "unsigned long \fBTimLibExtBlock::PllUtcPhasErr\fP"
.PP
Phase error Utc 
.SS "unsigned long \fBTimLibExtBlock::RecBadCycles\fP"
.PP
Number of bad reception cycles since last power up 
.SS "unsigned long \fBTimLibExtBlock::RecRcvdFrms\fP"
.PP
Number of received frames since last power up 
.SS "unsigned long \fBTimLibExtBlock::RecSentFrms\fP"
.PP
Value of last sent frames event 
.SS "\fBTimLibTime\fP \fBTimLibExtBlock::StartOne\fP"
.PP
Time of the last External-1 start 
.SS "unsigned long \fBTimLibExtBlock::Temperature\fP"
.PP
Temperature in units of 0.5 degrees C 
.SS "unsigned long \fBTimLibExtBlock::Valid\fP"
.PP
0 means invalid 

.SH "Author"
.PP 
Generated automatically by Doxygen for Low Level Timing Library from the source code.
