.TH "TimLibPllBlock" 3 "12 Nov 2008" "Low Level Timing Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimLibPllBlock \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBValid\fP"
.br
.ti -1c
.RI "unsigned long \fBError\fP"
.br
.ti -1c
.RI "unsigned long \fBIntegrator\fP"
.br
.ti -1c
.RI "unsigned long \fBDac\fP"
.br
.ti -1c
.RI "unsigned long \fBLastItLen\fP"
.br
.ti -1c
.RI "unsigned long \fBKI\fP"
.br
.ti -1c
.RI "unsigned long \fBKP\fP"
.br
.ti -1c
.RI "unsigned long \fBNumAverage\fP"
.br
.ti -1c
.RI "unsigned long \fBPhase\fP"
.br
.ti -1c
.RI "float \fBAsPrdNs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
PLL status block 
.PP
.SH "Member Data Documentation"
.PP 
.SS "float \fBTimLibPllBlock::AsPrdNs\fP"
.PP
Asynchronous period 
.SS "unsigned long \fBTimLibPllBlock::Dac\fP"
.PP
Value on DAC 
.SS "unsigned long \fBTimLibPllBlock::Error\fP"
.PP
Phase error 
.SS "unsigned long \fBTimLibPllBlock::Integrator\fP"
.PP
Integrator value 
.SS "unsigned long \fBTimLibPllBlock::KI\fP"
.PP
Constant of integration 
.SS "unsigned long \fBTimLibPllBlock::KP\fP"
.PP
Constant of proportionality 
.SS "unsigned long \fBTimLibPllBlock::LastItLen\fP"
.PP
Last iteration length 
.SS "unsigned long \fBTimLibPllBlock::NumAverage\fP"
.PP
Numeric average 
.SS "unsigned long \fBTimLibPllBlock::Phase\fP"
.PP
Pll phase 
.SS "unsigned long \fBTimLibPllBlock::Valid\fP"
.PP
0 means invalid 

.SH "Author"
.PP 
Generated automatically by Doxygen for Low Level Timing Library from the source code.
