.TH "TimLib" 3 "12 Nov 2008" "Low Level Timing Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimLib \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Julian Lewis AB/CO/HT April 2004. 
.RE
.PP
\fBVersion:\fP
.RS 4
23/Aug/2004
.RE
.PP
Low level timing library interface. This API will be implemented on all timing receiver cards, on all the CTR species, and TG8 cards. As long as only this interface is used, higher level implementations will remain hardware independent, so one FESA class can pilot all. Some functionality will not be available on the TG8s. The existance of the Telegram library is assumed. These library routines will be available on Linux platforms where the CTR PMC/PCI timing receiver cards are installed.
.PP
Testing your code and timlib can be achieved with the help of the test program. The 'timtest' program is available at
.PP
/usr/local/bin/timtest
.PP
To see a complete list of available commands type h 
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for Low Level Timing Library from the source code.
