.TH "TimLibTime" 3 "12 Nov 2008" "Low Level Timing Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TimLibTime \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned long \fBSecond\fP"
.br
.ti -1c
.RI "unsigned long \fBNano\fP"
.br
.ti -1c
.RI "unsigned long \fBCTrain\fP"
.br
.ti -1c
.RI "TgmMachine \fBMachine\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The time comes in the UTC second, the nanosecond in the second, and the millisecond modulo which is called the CTrain value. As each timing cable has a different CTrain value, for example the CPS and the PSB have different CTrains, it is important to know on which GMT cable the relavent device is connected; this explains the Machine parameter in the TimLibTime structure. 
.PP
.SH "Member Data Documentation"
.PP 
.SS "unsigned long \fBTimLibTime::CTrain\fP"
.PP
Machine millisecond in cycle 
.SS "TgmMachine \fBTimLibTime::Machine\fP"
.PP
Machine 
.SS "unsigned long \fBTimLibTime::Nano\fP"
.PP
Nano second in the second 
.SS "unsigned long \fBTimLibTime::Second\fP"
.PP
UTC Second 

.SH "Author"
.PP 
Generated automatically by Doxygen for Low Level Timing Library from the source code.
